import { inflateSync } from 'node:zlib';
import { describe, expect, it, vi } from 'vitest';
import { PDFDocument, StandardFonts } from 'pdf-lib';
import type { Exhibit } from '../lib/types';

/**
 * What the generated packet actually says, read out of the generated bytes.
 *
 * The planner is unit-tested next door, but a correct planner nobody consults
 * is worth nothing: the original defect was that drawExhibit decided from
 * `isPdfExhibit(e)` alone, which is true whether or not the bytes ever loaded.
 * A source-level assertion does not catch that (an `if (false && ...)` mutation
 * sails straight past a substring check), so this file inflates the PDF's own
 * content streams and asserts on the sentences a reader would see.
 *
 * The words are the contract here. A packet offered as a case record may not
 * promise a document it does not carry.
 */

const buffers = new Map<string, Buffer | null>();

vi.mock('../lib/storage', async (importOriginal) => {
  const actual = await importOriginal<Record<string, unknown>>();
  return {
    ...actual,
    getExhibitFileBuffer: async (e: { id: string }) => {
      if (!buffers.has(e.id)) return null;
      const b = buffers.get(e.id);
      if (b === null) throw new Error('storage read failed');
      return b;
    },
  };
});

const { generateCasePdf } = await import('../lib/pdf');

const PNG = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
  'base64',
);

async function makePdf(pages: number, text: string | null): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  for (let i = 0; i < pages; i++) {
    const p = doc.addPage([612, 792]);
    if (text) p.drawText(`${text} ${i + 1}`, { x: 60, y: 700, size: 18, font });
  }
  return Buffer.from(await doc.save());
}

/**
 * Pull the readable text out of a PDF by inflating every Flate content stream
 * and collecting the literal strings PDFKit writes for `Tj` / `TJ`.
 */
function showTextChunk(raw: string): string {
  const out: string[] = [];
  // A show-text operand is a run of hex strings and/or literal strings,
  // interleaved with kerning numbers that carry no text.
  for (const s of raw.matchAll(/<([0-9A-Fa-f\s]*)>|\(((?:\\.|[^\\()])*)\)/g)) {
    if (s[1] !== undefined) {
      const bytes = Buffer.from(s[1].replace(/\s+/g, ''), 'hex');
      // Drop the NUL padding a 2-byte CID encoding leaves behind.
      out.push(bytes.toString('latin1').replace(/\0/g, ''));
    } else {
      out.push((s[2] ?? '').replace(/\\([()\\])/g, '$1'));
    }
  }
  return out.join('');
}

function packetText(pdf: Buffer): string {
  const latin = pdf.toString('latin1');
  const out: string[] = [];
  // Anchor on `stream` that is not the tail of `endstream`.
  const re = /(^|[^d])stream\r?\n/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(latin)) !== null) {
    const start = m.index + m[0].length;
    const end = latin.indexOf('endstream', start);
    if (end < 0) continue;
    let decoded: string;
    try {
      decoded = inflateSync(pdf.subarray(start, end)).toString('latin1');
    } catch {
      continue;
    }
    // PDFKit emits `[<hex> 40 <hex>] TJ`; pdf-lib emits `<hex> Tj`.
    for (const s of decoded.matchAll(/\[([^\]]*)\]\s*TJ/g)) {
      out.push(showTextChunk(s[1]));
    }
    for (const s of decoded.matchAll(/(<[0-9A-Fa-f\s]*>|\((?:\\.|[^\\()])*\))\s*Tj/g)) {
      out.push(showTextChunk(s[1]));
    }
  }
  return out.join(' ');
}

function exhibit(over: Partial<Exhibit>): Exhibit {
  return {
    id: 'x',
    caseId: 'case-1',
    label: 'Exhibit A',
    fileName: 'file.pdf',
    storedFileName: 'file.pdf',
    fileType: 'application/pdf',
    fileSize: 1000,
    description: '',
    incidentDate: null,
    source: null,
    category: null,
    scanData: null,
    uploadedAt: '2026-08-01T00:00:00.000Z',
    ...over,
  } as Exhibit;
}

const CASE_RECORD = {
  id: 'case-1',
  title: 'Probe Case',
  caseType: 'landlord_tenant',
  description: 'A controlled mix of exhibit types.',
  jurisdiction: { city: 'Eden Prairie', state: 'MN', country: 'United States' },
  status: 'under_review',
  createdAt: '2026-08-01T00:00:00.000Z',
  updatedAt: '2026-08-01T00:00:00.000Z',
};

async function buildPacket(exhibits: Exhibit[]) {
  const pdf = await generateCasePdf({
    caseRecord: CASE_RECORD as never,
    exhibits,
    review: null,
    profile: null,
    clientName: 'Probe User',
    trial: false,
    reviewEntitled: false,
  });
  return { pdf, text: packetText(pdf) };
}

describe('a packet never promises a document it does not carry', () => {
  it('says the document follows only for the exhibit whose pages it merged', async () => {
    const good = await makePdf(3, 'REAL LEASE TEXT page');

    buffers.clear();
    buffers.set('good', good);
    buffers.set('unreadable', null);

    const { text } = await buildPacket([
      exhibit({ id: 'good', label: 'Exhibit A', fileName: 'lease.pdf', fileSize: good.length }),
      exhibit({
        id: 'unreadable',
        label: 'Exhibit B',
        fileName: 'missing.pdf',
        fileSize: 5000,
      }),
    ]);

    const promises = text.match(/Full document follows/g) ?? [];
    expect(promises).toHaveLength(1);
    expect(text).toMatch(/Not reproduced in this packet/);
    expect(text).toMatch(/could not be read from storage/);
    // "Full document" has to mean the whole document, so every page of it is
    // really in the packet.
    expect(text).toContain('REAL LEASE TEXT page 1');
    expect(text).toContain('REAL LEASE TEXT page 2');
    expect(text).toContain('REAL LEASE TEXT page 3');
  }, 60000);

  it('names an oversized file as not reproduced instead of promising it', async () => {
    buffers.clear();

    const { text } = await buildPacket([
      exhibit({
        id: 'huge',
        label: 'Exhibit A',
        fileName: 'deposition.pdf',
        fileSize: 25 * 1024 * 1024,
      }),
    ]);

    expect(text).not.toMatch(/Full document follows/);
    expect(text).toMatch(/Not reproduced in this packet/);
    expect(text).toMatch(/too large to reproduce/);
  }, 60000);

  it('names an all-blank document as having nothing to reproduce', async () => {
    const blank = await makePdf(3, null);
    buffers.clear();
    buffers.set('blank', blank);

    const { text } = await buildPacket([
      exhibit({ id: 'blank', label: 'Exhibit A', fileName: 'scan.pdf', fileSize: blank.length }),
    ]);

    expect(text).not.toMatch(/Full document follows/);
    expect(text).toMatch(/Every page of this document is blank/);
  }, 60000);

  it('does not describe an iPhone photo as a non-image attachment', async () => {
    buffers.clear();
    buffers.set('heic', Buffer.from('ftypheic pretend'));

    const { text } = await buildPacket([
      exhibit({
        id: 'heic',
        label: 'Exhibit A',
        fileName: 'IMG_0001.heic',
        fileType: 'image/heic',
        fileSize: 900000,
      }),
    ]);

    expect(text).toMatch(/This image format/);
    expect(text).not.toMatch(/Non-image attachments are referenced here/);
  }, 60000);

  it('still says non-image attachment for something that really is one', async () => {
    buffers.clear();
    buffers.set('audio', Buffer.from('fake audio'));

    const { text } = await buildPacket([
      exhibit({
        id: 'audio',
        label: 'Exhibit A',
        fileName: 'voicemail.m4a',
        fileType: 'audio/mp4',
        fileSize: 400000,
      }),
    ]);

    expect(text).toMatch(/Non-image attachments are referenced here/);
  }, 60000);

  it('says how much of a document over the per-exhibit cap was reproduced', async () => {
    const long = await makePdf(45, 'DEPOSITION page');
    buffers.clear();
    buffers.set('long', long);

    const { text } = await buildPacket([
      exhibit({ id: 'long', label: 'Exhibit A', fileName: 'depo.pdf', fileSize: long.length }),
    ]);

    expect(text).not.toMatch(/Full document follows/);
    expect(text).toMatch(/First 40 pages of 45 follow/);
    // The count on the page has to be the count in the packet. Claiming 40 and
    // merging some other number is the same defect wearing a new sentence.
    expect(text).toContain('DEPOSITION page 40');
    expect(text).not.toContain('DEPOSITION page 41');
  }, 60000);

  it('gives every exhibit a page, whatever became of its bytes', async () => {
    const good = await makePdf(2, 'GOOD page');
    buffers.clear();
    buffers.set('a', PNG);
    buffers.set('b', good);
    buffers.set('c', null);

    const { text } = await buildPacket([
      exhibit({ id: 'a', label: 'Exhibit A', fileName: 'p.png', fileType: 'image/png', fileSize: PNG.length }),
      exhibit({ id: 'b', label: 'Exhibit B', fileName: 'l.pdf', fileSize: good.length }),
      exhibit({ id: 'c', label: 'Exhibit C', fileName: 'x.pdf', fileSize: 900 }),
      exhibit({ id: 'd', label: 'Exhibit D', fileName: 'big.pdf', fileSize: 30 * 1024 * 1024 }),
    ]);

    for (const label of ['Exhibit A', 'Exhibit B', 'Exhibit C', 'Exhibit D']) {
      expect(text, `${label} has no page in the packet`).toContain(label);
    }
  }, 60000);
});
