import { inflateSync } from 'node:zlib';
import { describe, expect, it, vi } from 'vitest';
import type { Exhibit } from '../lib/types';

/**
 * What a court packet says about where a transcript came from, read out of the
 * generated bytes.
 *
 * NOT a source-level check. Green tests and a reviewed diff have both missed
 * defects here that were obvious on the rendered page, so this builds the
 * actual PDF, inflates its content streams and asserts on the sentences a
 * judge would read. The text extraction is the same approach
 * tests/export-packet-says-what-it-omits.test.ts uses.
 *
 * The risk being tested is one sentence wide. A packet that printed a
 * transcript the case owner typed under a heading saying software produced it
 * would let a court treat one person's account of what was said as an
 * independent reading of the recording.
 *
 * Mutations that turn these red are recorded at the bottom of this file.
 */

vi.mock('../lib/storage', async (importOriginal) => {
  const actual = await importOriginal<Record<string, unknown>>();
  return { ...actual, getExhibitFileBuffer: async () => null };
});

const { generateCasePdf } = await import('../lib/pdf');
const {
  MANUAL_TRANSCRIPT_MODEL,
  PACKET_TRANSCRIPT_PRINT_CHARS,
  buildManualTranscriptScan,
} = await import('../lib/manual-transcript');

function showTextChunk(raw: string): string {
  const out: string[] = [];
  for (const s of raw.matchAll(/<([0-9A-Fa-f\s]*)>|\(((?:\\.|[^\\()])*)\)/g)) {
    if (s[1] !== undefined) {
      const bytes = Buffer.from(s[1].replace(/\s+/g, ''), 'hex');
      out.push(bytes.toString('latin1').replace(/\0/g, ''));
    } else {
      out.push((s[2] ?? '').replace(/\\([()\\])/g, '$1'));
    }
  }
  return out.join('');
}

function packetText(pdf: Buffer): string {
  const latin = pdf.toString('latin1');
  const out: string[] = [];
  const re = /(^|[^d])stream\r?\n/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(latin)) !== null) {
    const start = m.index + m[0].length;
    const end = latin.indexOf('endstream', start);
    if (end < 0) continue;
    let decoded: string;
    try {
      decoded = inflateSync(pdf.subarray(start, end)).toString('latin1');
    } catch {
      continue;
    }
    for (const s of decoded.matchAll(/\[([^\]]*)\]\s*TJ/g)) out.push(showTextChunk(s[1]));
    for (const s of decoded.matchAll(
      /(<[0-9A-Fa-f\s]*>|\((?:\\.|[^\\()])*\))\s*Tj/g,
    )) {
      out.push(showTextChunk(s[1]));
    }
  }
  return out.join(' ');
}

const CASE_RECORD = {
  id: 'case-1',
  title: 'Probe Case',
  caseType: 'landlord_tenant',
  description: 'A recording and its transcript.',
  jurisdiction: { city: 'Eden Prairie', state: 'MN', country: 'United States' },
  status: 'under_review',
  createdAt: '2026-08-01T00:00:00.000Z',
  updatedAt: '2026-08-01T00:00:00.000Z',
};

function recording(scanData: unknown): Exhibit {
  return {
    id: 'ex-1',
    caseId: 'case-1',
    label: 'Exhibit A',
    fileName: 'kitchen argument.m4a',
    storedFileName: 'kitchen argument.m4a',
    fileType: 'audio/mp4',
    fileSize: 4_100_000,
    description: 'The recording from the kitchen',
    incidentDate: null,
    source: null,
    category: null,
    scanData,
    uploadedAt: '2026-08-01T00:00:00.000Z',
  } as unknown as Exhibit;
}

async function packet(exhibits: Exhibit[]): Promise<string> {
  const pdf = await generateCasePdf({
    caseRecord: CASE_RECORD as never,
    exhibits,
    review: null,
    profile: null,
    clientName: 'Probe User',
    trial: false,
    reviewEntitled: false,
  });
  return packetText(pdf);
}

const TYPED = 'SPEAKER 1: I never signed that. SPEAKER 2: You did, twice.';

function machineScan(transcript: string) {
  return {
    docType: 'voice_note',
    identifiers: {},
    parties: [],
    dates: [],
    summary: transcript,
    transcript,
    scannedAt: '2026-08-20T00:00:00.000Z',
    modelUsed: 'whisper-1',
  };
}

describe('the packet carries the transcript at all', () => {
  it('prints the words of a transcript the owner typed', async () => {
    const text = await packet([
      recording(buildManualTranscriptScan({ text: TYPED, isVideo: false, now: '2026-08-22T10:00:00.000Z' })),
    ]);
    expect(text).toContain('I never signed that');
    expect(text).toContain('You did, twice');
  });

  it('prints a machine transcript too', async () => {
    const text = await packet([recording(machineScan(TYPED))]);
    expect(text).toContain('I never signed that');
  });
});

describe('the packet says which kind of transcript it is', () => {
  it('names the case owner over a transcript they typed', async () => {
    const text = await packet([
      recording(buildManualTranscriptScan({ text: TYPED, isVideo: false, now: '2026-08-22T10:00:00.000Z' })),
    ]);
    expect(text).toMatch(/typed in by the case owner/i);
    expect(text).toMatch(/not produced by transcription software/i);
  });

  it('never claims software produced a transcript a person typed', async () => {
    const text = await packet([
      recording(buildManualTranscriptScan({ text: TYPED, isVideo: false, now: '2026-08-22T10:00:00.000Z' })),
    ]);
    expect(text).not.toMatch(/Transcript, produced by transcription software/i);
    expect(text).not.toMatch(/produced automatically/i);
  });

  it('names the software over a transcript the software produced', async () => {
    const text = await packet([recording(machineScan(TYPED))]);
    expect(text).toMatch(/produced by transcription software/i);
    expect(text).toMatch(/produced automatically/i);
    expect(text).not.toMatch(/typed in by the case owner/i);
  });

  it('does not print the internal marker as if it were a model name', async () => {
    const text = await packet([
      recording(buildManualTranscriptScan({ text: TYPED, isVideo: false, now: '2026-08-22T10:00:00.000Z' })),
    ]);
    expect(text).not.toContain(MANUAL_TRANSCRIPT_MODEL);
  });
});

describe('what the packet leaves out, it says it left out', () => {
  it('announces the cut on a transcript longer than it prints', async () => {
    const long = 'The witness said something at length. '.repeat(2000);
    expect(long.length).toBeGreaterThan(PACKET_TRANSCRIPT_PRINT_CHARS);
    const text = await packet([
      recording(buildManualTranscriptScan({ text: long, isVideo: false, now: '2026-08-22T10:00:00.000Z' })),
    ]);
    expect(text).toMatch(/This transcript runs to/i);
    expect(text).toContain(long.length.toLocaleString('en-US'));
    expect(text).toMatch(/has not been cut from it/i);
  });

  it('says nothing about a cut when it printed the whole thing', async () => {
    const text = await packet([
      recording(buildManualTranscriptScan({ text: TYPED, isVideo: false, now: '2026-08-22T10:00:00.000Z' })),
    ]);
    expect(text).not.toMatch(/This transcript runs to/i);
  });
});

describe('a placeholder scan puts nothing in a legal file', () => {
  it('prints no transcript section for a demo scan', async () => {
    const text = await packet([
      recording({
        docType: 'voice_note',
        identifiers: {},
        parties: [],
        dates: [],
        summary: 'Transcription is not available on this deployment.',
        transcript: 'Transcription is not available on this deployment.',
        scannedAt: '2026-08-20T00:00:00.000Z',
        modelUsed: 'unsupported',
        isDemo: true,
      }),
    ]);
    expect(text).not.toMatch(/Transcript, /i);
    expect(text).not.toMatch(/not available on this deployment/i);
  });

  it('prints no transcript section when there is no transcript', async () => {
    const text = await packet([recording(null)]);
    expect(text).not.toMatch(/Transcript, /i);
  });
});

/*
 * MUTATIONS RUN AGAINST THIS FILE. Each was applied, confirmed red, reverted,
 * and `git diff --stat` confirmed empty afterwards.
 *
 *   Make transcriptOriginHeading always return the machine sentence, so a
 *   typed transcript is printed as the software's: red here.
 *
 *   Drop the isRealScan gate in drawTranscript, so a placeholder's text is
 *   printed into a legal file: red here.
 *
 *   Make packetTranscriptBody slice without returning a note, so the cut is
 *   silent: red here.
 */
