'use client';

import { useEffect, useRef, useState } from 'react';
import { Dialog } from './Dialog';
import { PdfViewer } from './PdfViewer';
import { T } from './i18n/LocaleProvider';

/**
 * In-app PDF preview for documents generated by the app (employee NDA/forms,
 * counsel letters, templates). Opens the EXACT bytes the export produces in
 * an embedded viewer, so what the person approves is what prints/sends,
 * not the plain-text approximation next to the form.
 *
 * Flow: caller passes buildPdf (the same function its Download button uses);
 * we build once, draw it with PdfViewer, and offer Print / Download /
 * "make changes" (close). The blob URL is revoked on unmount.
 *
 * THE BLOB AND THE VIEWER SHOW THE SAME BYTES BY CONSTRUCTION. The
 * viewer is handed the Blob itself rather than the object URL, and the
 * object URL exists only for Print, Download and the new-tab link. So
 * there is one build, and the document somebody approves is the file
 * that leaves.
 *
 * This used to be an `<iframe src={blobUrl}>`, and what the reader got
 * was the browser's own PDF plugin: Chrome titled their letter with the
 * blob's UUID and put a second Download and a second Print next to
 * ours, saving under a name that was not the document's; some mobile
 * WebViews rendered nothing at all and the iframe's onLoad still fired,
 * so there was no way to notice. PdfViewer draws the page itself, with
 * page navigation, zoom, and a failure state that says what happened.
 * The "Open in a new tab" link stays, because a reader who wants the
 * text rather than the picture of it should have the real file.
 */
export function PdfPreviewDialog({
  title,
  filename,
  buildPdf,
  onClose,
  actions,
  note,
}: {
  title: string;
  filename: string;
  buildPdf: () => Promise<Blob>;
  onClose: () => void;
  /** Extra footer buttons (e.g. "Looks good, send") rendered next to the defaults. */
  actions?: React.ReactNode;
  /**
   * What this preview is NOT, on the surfaces where the honest answer is not
   * "the file that goes out".
   *
   * A letter is saved as Word, and a template has blanks nobody has answered
   * yet. Both are real differences between these bytes and the artifact the
   * other side ends up with, and a preview that let someone believe otherwise
   * would be worse than no preview: it manufactures confidence about a
   * document leaving the firm. Stated above the viewer, before the document is
   * read, rather than in a footnote under it.
   */
  note?: React.ReactNode;
}) {
  const [url, setUrl] = useState<string | null>(null);
  const [blob, setBlob] = useState<Blob | null>(null);
  const [error, setError] = useState<string | null>(null);
  const urlRef = useRef<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const built = await buildPdf();
        if (cancelled) return;
        const u = URL.createObjectURL(built);
        urlRef.current = u;
        setBlob(built);
        setUrl(u);
      } catch (e) {
        if (!cancelled) {
          setError(e instanceof Error ? e.message : 'Could not prepare the preview.');
        }
      }
    })();
    return () => {
      cancelled = true;
      if (urlRef.current) URL.revokeObjectURL(urlRef.current);
    };
    // buildPdf is intentionally captured once: the preview shows the
    // document as it was when opened; edits require closing and reopening.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const print = () => {
    if (!url) return;
    const w = window.open(url, '_blank');
    w?.addEventListener('load', () => w.print());
  };

  const download = () => {
    if (!url) return;
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
  };

  return (
    <Dialog onClose={onClose} ariaLabel={title} size="lg" elevated>
      <div className="flex flex-col gap-3">
        <header className="flex flex-wrap items-center justify-between gap-2">
          <div className="min-w-0">
            {/* text-muted, not text-ink-400. The light counsel layer in
                app/globals.css repaints the cream classes and not the
                ink ones, so an ink step is measured in dark and falls
                through to a raw value in light. A token has one
                declaration per theme and cannot go unrepainted. */}
            <p className="text-[11px] font-semibold uppercase tracking-wider text-muted">
              <T>Preview before you print or send</T>
            </p>
            <h2 className="truncate font-display text-lg font-medium text-forest-900 dark:text-cream-100">
              {title}
            </h2>
          </div>
          {url && (
            <a
              href={url}
              target="_blank"
              rel="noreferrer"
              className="text-[12.5px] text-muted underline hover:text-foreground"
            >
              <T>Open in a new tab</T>
            </a>
          )}
        </header>

        {note && (
          <p className="rounded-lg border border-ink-200 bg-cream-50/60 px-3 py-2 text-[12.5px] leading-relaxed text-ink-600 dark:border-forest-700/50 dark:bg-forest-900/60 dark:text-cream-100/70">
            {note}
          </p>
        )}

        {error ? (
          <p className="rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-[13px] text-rose-800 dark:border-rose-700/40 dark:bg-rose-950/40 dark:text-rose-200">
            {error}
          </p>
        ) : blob ? (
          // Rounded and clipped here rather than inside the viewer: the
          // viewer is also mounted flush inside a card, where corners
          // would be wrong.
          <div className="overflow-hidden rounded-lg border border-edge">
            <PdfViewer
              source={{ kind: 'blob', blob }}
              title={title}
              className="h-[58dvh] w-full"
              fallbackHref={url ?? undefined}
            />
          </div>
        ) : (
          <div className="flex h-[58dvh] items-center justify-center rounded-lg border border-dashed border-edge text-[13.5px] text-muted">
            <T>Preparing the document…</T>
          </div>
        )}

        <footer className="flex flex-wrap items-center justify-end gap-2 border-t border-ink-100 pt-3 dark:border-forest-800/50">
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg border border-ink-200 px-4 py-2 text-[14px] font-medium text-forest-900 hover:bg-cream-50 dark:border-forest-700/50 dark:text-cream-100 dark:hover:bg-forest-800/50"
          >
            <T>Close &amp; make changes</T>
          </button>
          <button
            type="button"
            disabled={!url}
            onClick={print}
            className="rounded-lg border border-ink-200 px-4 py-2 text-[14px] font-medium text-forest-900 hover:bg-cream-50 disabled:opacity-50 dark:border-forest-700/50 dark:text-cream-100 dark:hover:bg-forest-800/50"
          >
            <T>Print</T>
          </button>
          <button
            type="button"
            disabled={!url}
            onClick={download}
            className="btn-primary disabled:opacity-50"
          >
            <T>Download PDF</T>
          </button>
          {actions}
        </footer>
      </div>
    </Dialog>
  );
}
