import {
  AlignmentType,
  BorderStyle,
  Document,
  Header,
  Footer,
  HeadingLevel,
  ImageRun,
  Packer,
  PageNumber,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx';
import type { CommunityExportData } from './community-types';
import type { ClosingLine } from './letter-compose';
import {
  letterheadDesignWordLines,
  type LetterheadDesign,
} from './letterhead-design';
import { formatDateNumeric, formatDateTimeNumeric } from './format';
import { accentTextOnDocument } from './accent-text';

/**
 * Word export of a Community Case's submissions, mirroring the structure
 * of generateCommunitySubmissionsPdf in lib/pdf.ts (same CommunityExportData
 * input, same cover-page-then-one-section-per-submission shape) so the two
 * formats stay in sync without a shared rendering engine - docx and PDFKit
 * have too different an API surface to unify further than "same input
 * shape, same section order."
 */
export async function generateCommunitySubmissionsDocx(input: CommunityExportData): Promise<Buffer> {
  const children: Array<Paragraph | Table> = [];

  children.push(
    new Paragraph({
      spacing: { after: 100 },
      children: [new TextRun({ text: 'COMMUNITY CASE PACKET', color: '71717A', size: 16, bold: true })],
    }),
  );
  children.push(
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun({ text: input.communityCase.displayName, bold: true })],
    }),
  );
  children.push(metaTable([
    ['Case number', input.communityCase.caseNumber],
    ['Status', input.communityCase.status],
    ['Exported', formatDateTimeNumeric(Date.now())],
    ['Letters of Support', String(input.communityCase.letterCount)],
    ['Evidence / testimonials', String(input.communityCase.evidenceCount)],
  ]));
  children.push(spacer());

  if (input.communityCase.publicSummary) {
    children.push(heading("Organizer's public summary"));
    children.push(new Paragraph({ text: input.communityCase.publicSummary }));
    children.push(spacer());
  }

  // Organizer identity block - same rationale as drawCommunityCoverPage in
  // lib/pdf.ts: this is the concrete artifact that lets an attorney or a
  // fraud investigation trace a page back to a real, verified account.
  // Confidential; never rendered on the public page.
  children.push(heading('Organizer (verified Advottic account): for your records only'));
  children.push(
    new Paragraph({
      text: `${input.organizer.name} · ${input.organizer.email}${
        input.organizer.accountCreatedAt
          ? ` · account created ${formatDateNumeric(input.organizer.accountCreatedAt)}`
          : ''
      }`,
    }),
  );
  children.push(spacer());
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: 'These links go directly to the organizer’s own accounts. Advottic never processes or holds any funds.',
          italics: true,
          color: '71717A',
          size: 18,
        }),
      ],
    }),
  );

  for (const s of input.submissions) {
    children.push(new Paragraph({ pageBreakBefore: true, text: '' }));
    children.push(...(await submissionSection(s)));
  }

  children.push(new Paragraph({ pageBreakBefore: true, text: '' }));
  children.push(heading('About this export'));
  children.push(
    new Paragraph({
      text:
        'This packet was generated by Advottic from a Community Case page. Submissions are provided as-is by members of the public; Advottic does not verify their accuracy. This is not legal advice.',
    }),
  );

  const doc = new Document({
    sections: [
      {
        properties: {},
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [new TextRun({ text: input.communityCase.displayName, size: 16, color: '71717A' })],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ children: [PageNumber.CURRENT], size: 16, color: '71717A' }),
                  new TextRun({ text: ' of ', size: 16, color: '71717A' }),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: '71717A' }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  return Packer.toBuffer(doc);
}

function heading(text: string): Paragraph {
  return new Paragraph({ heading: HeadingLevel.HEADING_2, text, spacing: { before: 200, after: 100 } });
}

function spacer(): Paragraph {
  return new Paragraph({ text: '' });
}

function metaTable(rows: Array<[string, string | null]>): Table {
  const filtered = rows.filter(([, v]) => v);
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: {
      top: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
      bottom: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
      left: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
      right: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
      insideHorizontal: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
      insideVertical: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
    },
    rows: filtered.map(
      ([label, value]) =>
        new TableRow({
          children: [
            new TableCell({
              width: { size: 35, type: WidthType.PERCENTAGE },
              children: [new Paragraph({ children: [new TextRun({ text: label.toUpperCase(), size: 16, color: '71717A', bold: true })] })],
            }),
            new TableCell({
              width: { size: 65, type: WidthType.PERCENTAGE },
              children: [new Paragraph({ text: value ?? '' })],
            }),
          ],
        }),
    ),
  });
}

async function submissionSection(
  s: CommunityExportData['submissions'][number],
): Promise<Array<Paragraph | Table>> {
  const out: Array<Paragraph | Table> = [];
  out.push(
    new Paragraph({
      children: [new TextRun({ text: 'SUBMISSION: CONFIDENTIAL, NOT FOR PUBLIC DISTRIBUTION', size: 16, color: '71717A', bold: true })],
    }),
  );
  out.push(new Paragraph({ heading: HeadingLevel.HEADING_1, text: s.fullName || 'Anonymous submitter' }));

  if (s.kind === 'letter_of_support') {
    const addr = s.mailingAddress;
    out.push(
      metaTable([
        ['Submitted', formatDateTimeNumeric(s.createdAt)],
        ['Type', 'Letter of Support'],
        ['Mailing address', addr ? `${addr.street}, ${addr.city}, ${addr.state} ${addr.zip}` : null],
      ]),
    );
    out.push(spacer());

    if (s.letterBody) {
      out.push(heading('Letter'));
      for (const line of s.letterBody.split(/\n+/)) {
        out.push(new Paragraph({ text: line }));
      }
      out.push(spacer());
    }

    if (s.signatureBuffer) {
      out.push(heading('Signature'));
      out.push(imageParagraph(s.signatureBuffer, 280, 100));
      out.push(spacer());
    }

    if (s.idFrontBuffer) {
      out.push(heading('ID (front)'));
      out.push(imageParagraph(s.idFrontBuffer, 460, 260));
      out.push(spacer());
    }
    if (s.idBackBuffer) {
      out.push(heading('ID (back)'));
      out.push(imageParagraph(s.idBackBuffer, 460, 260));
      out.push(spacer());
    }
    return out;
  }

  out.push(
    metaTable([
      ['Submitted', formatDateTimeNumeric(s.createdAt)],
      ['Attachment', s.evidenceFileName ?? null],
      ['File size', s.evidenceFileSize ? formatBytes(s.evidenceFileSize) : null],
    ]),
  );
  out.push(spacer());

  if (s.testimonialText) {
    out.push(heading('Testimonial'));
    for (const line of s.testimonialText.split(/\n+/)) {
      out.push(new Paragraph({ text: line }));
    }
    out.push(spacer());
  }

  if (s.imageBuffer) {
    out.push(imageParagraph(s.imageBuffer, 460, 340));
  } else if (s.evidenceFileName && s.evidenceFileType === 'application/pdf') {
    out.push(
      new Paragraph({
        children: [new TextRun({ text: 'PDF attachment - available separately in the case file.', italics: true, color: '71717A' })],
      }),
    );
  }

  return out;
}

function imageParagraph(buffer: Buffer, width: number, height: number): Paragraph {
  try {
    return new Paragraph({
      children: [
        new ImageRun({
          data: buffer,
          transformation: { width, height },
          type: 'png',
        } as ConstructorParameters<typeof ImageRun>[0]),
      ],
    });
  } catch {
    return new Paragraph({
      children: [new TextRun({ text: '[image could not be embedded]', italics: true, color: '71717A' })],
    });
  }
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

// =====================================================================
// Letter export (#13)
// =====================================================================

export type LetterDocxInput = {
  firmName: string;
  /**
   * The letterhead the firm designed under /counsel/settings. When present it
   * IS the letterhead, and firmName + contactLine below are not drawn.
   */
  letterheadDesign?: LetterheadDesign | null;
  /** Optional sub-line under the firm name: address, jurisdictions, etc. */
  contactLine?: string | null;
  /** Firm accent, hex with or without leading '#'. */
  accentHex?: string | null;
  /** Optional bold document title under the letterhead. */
  title?: string | null;
  /** The letter body (salutation through closing paragraph). */
  body: string;
  /** Structured closing block from lib/letter-compose. */
  closing: ClosingLine[];
};

/**
 * Word (.docx) export of a generated letter (#13). Word letters use a
 * typographic letterhead rather than an embedded raster - it's editable,
 * deterministic, and avoids image-dimension math.
 *
 * WHERE THE LETTERHEAD COMES FROM. If the firm designed one under
 * /counsel/settings, the block is built from letterheadDesignWordLines, which
 * is the SAME layout the PDF renderer draws, converted into Word's units.
 * Nothing about the order or the emphasis is decided here. A firm that typed
 * its address once should not find that its Word export and its PDF describe
 * different stationery, which is the whole point of the feature. Failing a
 * design, the old block (firm name in the accent color plus a contact
 * sub-line) is the fallback, and it plays the same role the PDF's text-only
 * banner does.
 *
 * WHAT DOES NOT SURVIVE THE CROSSING, stated rather than approximated:
 *
 *   - The accent bar the PDF paints across the very top of the page. Word has
 *     no page-edge rectangle short of a floating shape, and a floating shape
 *     in a document a lawyer is about to edit is worse than its absence.
 *   - Repetition. The PDF paints the letterhead on EVERY page; this block sits
 *     once at the top of the document body. Moving it into a Word Header would
 *     repeat it, but it would also relayout every letter this product has
 *     already exported, so it stays in the body.
 *   - The uploaded letterhead IMAGE, which this export has never drawn and
 *     still does not. So a firm holding both an image and a design gets the
 *     image on the PDF and the design in Word. That is a narrower gap than the
 *     one that existed before, not a new one.
 *
 * Type size, the line gap and the rule weight DO cross intact: Word measures
 * type in half-points and spacing in twentieths of a point, and both are exact
 * multiples of the points the PDF uses.
 */
export async function generateLetterDocx(
  input: LetterDocxInput,
): Promise<Buffer> {
  const accentHex = (input.accentHex || '#0f2d24').slice(0, 7);
  const accent = accentHex.replace(/^#/, '').slice(0, 6);
  /**
   * The firm's name, as ink on a Word page.
   *
   * Same rule as the PDF and the two counsel studios, through the same function:
   * a colour picked to work as a fill is usually unreadable as text, and a Word
   * page is white. Advottic's own gold measured 1.87:1 here. The RULE below
   * keeps the raw accent, because a rule is a fill.
   */
  const accentInk = accentTextOnDocument(accentHex).replace(/^#/, '');
  const children: Array<Paragraph | Table> = [];

  const design = input.letterheadDesign ?? null;
  if (design) {
    const alignment =
      design.alignment === 'center' ? AlignmentType.CENTER : AlignmentType.LEFT;
    for (const line of letterheadDesignWordLines(design)) {
      children.push(
        new Paragraph({
          alignment,
          // The gap under the last line is widened, because that is where the
          // body starts rather than where the next letterhead line does.
          spacing: { after: line.rule ? 120 : line.spacingAfterTwips },
          border: line.rule
            ? {
                // size is in eighths of a point, so 4 is the 0.5pt hairline
                // the PDF renderer draws.
                bottom: { style: BorderStyle.SINGLE, size: 4, color: accent, space: 6 },
              }
            : undefined,
          children: [
            new TextRun({
              text: line.text,
              bold: line.bold,
              size: line.sizeHalfPoints,
              color: line.bold ? accentInk : '52525B',
            }),
          ],
        }),
      );
    }
  } else {
    // No design: the old typographic block, unchanged.
    children.push(
      new Paragraph({
        spacing: { after: 40 },
        children: [
          new TextRun({ text: input.firmName, bold: true, size: 30, color: accentInk }),
        ],
      }),
    );
    children.push(
      new Paragraph({
        spacing: { after: 120 },
        border: {
          bottom: { style: BorderStyle.SINGLE, size: 6, color: accent, space: 6 },
        },
        children: [
          new TextRun({
            text: input.contactLine?.trim() ?? '',
            size: input.contactLine?.trim() ? 18 : 2,
            color: '52525B',
          }),
        ],
      }),
    );
  }

  if (input.title && input.title.trim()) {
    children.push(
      new Paragraph({
        spacing: { before: 120, after: 120 },
        children: [new TextRun({ text: input.title.trim(), bold: true, size: 26 })],
      }),
    );
  }

  // Body: blank lines become spacers, everything else a paragraph.
  for (const line of input.body.split('\n')) {
    if (line.trim() === '') {
      children.push(spacer());
    } else {
      children.push(
        new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: line })] }),
      );
    }
  }

  // Closing block.
  children.push(spacer());
  for (const cl of input.closing) {
    if (cl.kind === 'blank') {
      children.push(spacer());
    } else if (cl.kind === 'rule') {
      // A signing line: a short paragraph with a bottom border.
      children.push(
        new Paragraph({
          spacing: { before: 60, after: 20 },
          border: {
            bottom: { style: BorderStyle.SINGLE, size: 6, color: '111111', space: 1 },
          },
          children: [new TextRun({ text: '', size: 2 })],
        }),
      );
    } else if (cl.kind === 'strong') {
      children.push(
        new Paragraph({ children: [new TextRun({ text: cl.text, bold: true })] }),
      );
    } else {
      children.push(new Paragraph({ children: [new TextRun({ text: cl.text })] }));
    }
  }

  const doc = new Document({
    sections: [
      {
        properties: {},
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ text: input.firmName + '  ·  ', size: 14, color: '9CA3AF' }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 14, color: '9CA3AF' }),
                ],
              }),
              // Travels-with-the-file draft caveat (audit Content M3).
              new Paragraph({
                alignment: AlignmentType.CENTER,
                spacing: { before: 40 },
                children: [
                  new TextRun({
                    text: 'Draft prepared with Advottic. Review by a licensed attorney is recommended before this letter is sent or filed.',
                    italics: true,
                    size: 13,
                    color: '9CA3AF',
                  }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  return Packer.toBuffer(doc);
}
