import {
  AlignmentType,
  BorderStyle,
  Document,
  Header,
  Footer,
  HeadingLevel,
  ImageRun,
  Packer,
  PageNumber,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx';
import type { CommunityExportData } from './community-types';

/**
 * Word export of a Community Case's submissions, mirroring the structure
 * of generateCommunitySubmissionsPdf in lib/pdf.ts (same CommunityExportData
 * input, same cover-page-then-one-section-per-submission shape) so the two
 * formats stay in sync without a shared rendering engine - docx and PDFKit
 * have too different an API surface to unify further than "same input
 * shape, same section order."
 */
export async function generateCommunitySubmissionsDocx(input: CommunityExportData): Promise<Buffer> {
  const children: Array<Paragraph | Table> = [];

  children.push(
    new Paragraph({
      spacing: { after: 100 },
      children: [new TextRun({ text: 'COMMUNITY CASE PACKET', color: '71717A', size: 16, bold: true })],
    }),
  );
  children.push(
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun({ text: input.communityCase.displayName, bold: true })],
    }),
  );
  children.push(metaTable([
    ['Case number', input.communityCase.caseNumber],
    ['Status', input.communityCase.status],
    ['Exported', new Date().toLocaleString()],
    ['Letters of Support', String(input.communityCase.letterCount)],
    ['Evidence / testimonials', String(input.communityCase.evidenceCount)],
  ]));
  children.push(spacer());

  if (input.communityCase.publicSummary) {
    children.push(heading("Organizer's public summary"));
    children.push(new Paragraph({ text: input.communityCase.publicSummary }));
    children.push(spacer());
  }

  // Organizer identity block - same rationale as drawCommunityCoverPage in
  // lib/pdf.ts: this is the concrete artifact that lets an attorney or a
  // fraud investigation trace a page back to a real, verified account.
  // Confidential; never rendered on the public page.
  children.push(heading('Organizer (verified Advottic account) — for your records only'));
  children.push(
    new Paragraph({
      text: `${input.organizer.name} · ${input.organizer.email}${
        input.organizer.accountCreatedAt
          ? ` · account created ${new Date(input.organizer.accountCreatedAt).toLocaleDateString()}`
          : ''
      }`,
    }),
  );
  children.push(spacer());
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: 'These links go directly to the organizer’s own accounts. Advottic never processes or holds any funds.',
          italics: true,
          color: '71717A',
          size: 18,
        }),
      ],
    }),
  );

  for (const s of input.submissions) {
    children.push(new Paragraph({ pageBreakBefore: true, text: '' }));
    children.push(...(await submissionSection(s)));
  }

  children.push(new Paragraph({ pageBreakBefore: true, text: '' }));
  children.push(heading('About this export'));
  children.push(
    new Paragraph({
      text:
        'This packet was generated by Advottic from a Community Case page. Submissions are provided as-is by members of the public; Advottic does not verify their accuracy. This is not legal advice.',
    }),
  );

  const doc = new Document({
    sections: [
      {
        properties: {},
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [new TextRun({ text: input.communityCase.displayName, size: 16, color: '71717A' })],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ children: [PageNumber.CURRENT], size: 16, color: '71717A' }),
                  new TextRun({ text: ' of ', size: 16, color: '71717A' }),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: '71717A' }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  return Packer.toBuffer(doc);
}

function heading(text: string): Paragraph {
  return new Paragraph({ heading: HeadingLevel.HEADING_2, text, spacing: { before: 200, after: 100 } });
}

function spacer(): Paragraph {
  return new Paragraph({ text: '' });
}

function metaTable(rows: Array<[string, string | null]>): Table {
  const filtered = rows.filter(([, v]) => v);
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: {
      top: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
      bottom: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
      left: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
      right: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
      insideHorizontal: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
      insideVertical: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
    },
    rows: filtered.map(
      ([label, value]) =>
        new TableRow({
          children: [
            new TableCell({
              width: { size: 35, type: WidthType.PERCENTAGE },
              children: [new Paragraph({ children: [new TextRun({ text: label.toUpperCase(), size: 16, color: '71717A', bold: true })] })],
            }),
            new TableCell({
              width: { size: 65, type: WidthType.PERCENTAGE },
              children: [new Paragraph({ text: value ?? '' })],
            }),
          ],
        }),
    ),
  });
}

async function submissionSection(
  s: CommunityExportData['submissions'][number],
): Promise<Array<Paragraph | Table>> {
  const out: Array<Paragraph | Table> = [];
  out.push(
    new Paragraph({
      children: [new TextRun({ text: 'SUBMISSION — CONFIDENTIAL, NOT FOR PUBLIC DISTRIBUTION', size: 16, color: '71717A', bold: true })],
    }),
  );
  out.push(new Paragraph({ heading: HeadingLevel.HEADING_1, text: s.fullName || 'Anonymous submitter' }));

  if (s.kind === 'letter_of_support') {
    const addr = s.mailingAddress;
    out.push(
      metaTable([
        ['Submitted', new Date(s.createdAt).toLocaleString()],
        ['Type', 'Letter of Support'],
        ['Mailing address', addr ? `${addr.street}, ${addr.city}, ${addr.state} ${addr.zip}` : null],
      ]),
    );
    out.push(spacer());

    if (s.letterBody) {
      out.push(heading('Letter'));
      for (const line of s.letterBody.split(/\n+/)) {
        out.push(new Paragraph({ text: line }));
      }
      out.push(spacer());
    }

    if (s.signatureBuffer) {
      out.push(heading('Signature'));
      out.push(imageParagraph(s.signatureBuffer, 280, 100));
      out.push(spacer());
    }

    if (s.idFrontBuffer) {
      out.push(heading('ID — front'));
      out.push(imageParagraph(s.idFrontBuffer, 460, 260));
      out.push(spacer());
    }
    if (s.idBackBuffer) {
      out.push(heading('ID — back'));
      out.push(imageParagraph(s.idBackBuffer, 460, 260));
      out.push(spacer());
    }
    return out;
  }

  out.push(
    metaTable([
      ['Submitted', new Date(s.createdAt).toLocaleString()],
      ['Attachment', s.evidenceFileName ?? null],
      ['File size', s.evidenceFileSize ? formatBytes(s.evidenceFileSize) : null],
    ]),
  );
  out.push(spacer());

  if (s.testimonialText) {
    out.push(heading('Testimonial'));
    for (const line of s.testimonialText.split(/\n+/)) {
      out.push(new Paragraph({ text: line }));
    }
    out.push(spacer());
  }

  if (s.imageBuffer) {
    out.push(imageParagraph(s.imageBuffer, 460, 340));
  } else if (s.evidenceFileName && s.evidenceFileType === 'application/pdf') {
    out.push(
      new Paragraph({
        children: [new TextRun({ text: 'PDF attachment - available separately in the case file.', italics: true, color: '71717A' })],
      }),
    );
  }

  return out;
}

function imageParagraph(buffer: Buffer, width: number, height: number): Paragraph {
  try {
    return new Paragraph({
      children: [
        new ImageRun({
          data: buffer,
          transformation: { width, height },
          type: 'png',
        } as ConstructorParameters<typeof ImageRun>[0]),
      ],
    });
  } catch {
    return new Paragraph({
      children: [new TextRun({ text: '[image could not be embedded]', italics: true, color: '71717A' })],
    });
  }
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
