import type { SignatureMethod } from './signature-methods';
/**
 * Type surface for the law-firm perspective ("Advottic Counsel").
 * Server boundary returns these shapes; everything inside firm-mode
 * routes consumes them.
 *
 * See docs/LAW_FIRM_MODE.md for the architecture overview.
 */

import { PILL_COLORS } from '@/lib/pill-colors';

// ---------------------------------------------------------------------------
// Firm type
// ---------------------------------------------------------------------------

export type FirmType =
  | 'individual'
  | 'firm'
  | 'corporate'
  | 'government'
  | 'legal_aid'
  | 'other';

export const FIRM_TYPES: FirmType[] = [
  'individual',
  'firm',
  'corporate',
  'government',
  'legal_aid',
  'other',
];

export const FIRM_TYPE_LABEL: Record<FirmType, string> = {
  individual: 'Individual counsel',
  firm: 'Law firm',
  corporate: 'Corporate / in-house counsel',
  government: 'Government / state',
  legal_aid: 'Legal aid / nonprofit',
  other: 'Other',
};

export const FIRM_TYPE_DESCRIPTION: Record<FirmType, string> = {
  individual:
    'A solo attorney or independent practitioner. You handle your own caseload and may bring in part-time staff.',
  firm: 'A traditional law firm with multiple attorneys, partners, and support staff working under a shared brand.',
  corporate:
    'An in-house legal team inside a company. Your client is the company itself - contracts, compliance, M&A, employment, regulatory.',
  government:
    'A government legal department - attorney general office, public defender, county counsel, agency legal team.',
  legal_aid:
    'A nonprofit, legal-aid clinic, or pro-bono organization that serves a population that cannot afford private counsel.',
  other:
    "Doesn't fit the above. Tell us what you do and we'll tailor the workspace to it.",
};

/** Free-form metadata captured during onboarding, conditional on
 *  firm type. The shape is intentionally loose so we can ask new
 *  questions without database migrations. Documented union types:
 *
 *  individual: { barNumber?: string; yearAdmitted?: number }
 *  firm:       { sizeBand?: '1-5'|'6-25'|'26-100'|'100+'; foundedYear?: number }
 *  corporate:  { parentCompany?: string; industry?: string; isGeneralCounsel?: boolean; businessAreas?: string[] }
 *  government: { agencyType?: string; governmentLevel?: 'federal'|'state'|'county'|'municipal'; caseFocus?: string[] }
 *  legal_aid:  { populationServed?: string; fundingSource?: string }
 *  other:      { description?: string }
 */
export type FirmMetadata = Record<string, unknown>;

export type FirmRole = 'owner' | 'admin' | 'attorney' | 'paralegal' | 'staff';

export const FIRM_ROLES: FirmRole[] = [
  'owner',
  'admin',
  'attorney',
  'paralegal',
  'staff',
];

export const FIRM_ROLE_LABEL: Record<FirmRole, string> = {
  owner: 'Owner',
  admin: 'Admin',
  attorney: 'Attorney',
  paralegal: 'Paralegal',
  staff: 'Staff',
};

export const FIRM_ROLE_DESCRIPTION: Record<FirmRole, string> = {
  owner:
    'Full control. Can change firm settings, billing, transfer ownership, and remove anyone.',
  admin:
    'Manage members, clients, channels, and documents. Cannot transfer ownership or close the firm.',
  attorney:
    'Read and edit cases, sign documents, message clients. Can invite clients.',
  paralegal:
    'Read and edit cases and documents. Can prepare signing requests but not send them.',
  staff:
    'Read-only access to non-privileged surfaces. Useful for receptionists or billing staff.',
};

export type Firm = {
  id: string;
  slug: string;
  name: string;
  firmType: FirmType;
  metadata: FirmMetadata;
  logoUrl: string | null;
  /**
   * Tier-2 Bella branding. The firm's letterhead - a wide PNG/JPG with
   * the firm's full mailing address, phone, partner names, bar IDs etc.
   * burned in. Painted across the top of any PDF generated by
   * draft-template/pdf when set. Different from logoUrl (which is a
   * small icon for the sidebar). Stored in the public firm-branding
   * bucket so the PDF generator can fetch it without auth.
   */
  letterheadUrl: string | null;
  accentColor: string;
  jurisdictions: string[];
  practiceAreas: string[];
  /**
   * Phase 2 white-label flag. When true the firm has been provisioned
   * a tenant subdomain at <slug>.advottic.com (DNS + Vercel domain
   * already registered, TLS issued). Toggled from HQ via the
   * provisionTenantSubdomainAction / revokeTenantSubdomainAction
   * server actions.
   */
  subdomainEnabled: boolean;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
};

export type FirmMember = {
  id: string;
  firmId: string;
  userId: string;
  role: FirmRole;
  displayName: string | null;
  email: string | null;
  joinedAt: string;
};

/**
 * A non-legal employee of an enterprise tenant. Deliberately NOT a
 * FirmMember (that implies a legal-team seat + the full Counsel app).
 * Employees only ever reach the scoped /portal/* surface. See
 * docs/ENTERPRISE_WORKSPACE.md and supabase/fixes/2026-05-18-firm-employees.sql.
 */
export type FirmEmployee = {
  id: string;
  firmId: string;
  userId: string | null;
  email: string;
  displayName: string | null;
  department: string | null;
  source: 'manual' | 'azure' | 'google';
  externalId: string | null;
  deactivatedAt: string | null;
  createdAt: string;
};

export type FirmInvitation = {
  id: string;
  firmId: string;
  email: string;
  role: FirmRole;
  invitedBy: string | null;
  token: string;
  expiresAt: string;
  acceptedAt: string | null;
  createdAt: string;
};

export type FirmClientStatus = 'invited' | 'active' | 'archived';

export type FirmClient = {
  id: string;
  firmId: string;
  userId: string;
  primaryAttorneyId: string | null;
  invitedBy: string | null;
  status: FirmClientStatus;
  joinedAt: string;
  /** Hydrated from auth.users when listed. */
  email?: string | null;
  /** Hydrated from profiles when listed. */
  displayName?: string | null;
};

// ---------- Documents + signing ----------

/**
 * Workflow state for a document. Documents in a law firm are
 * seldom signed in a vacuum - they belong to a case file, a
 * matter, or a ticket, and they pass through a real lifecycle.
 *
 *   received        - incoming from external party
 *   submitted       - uploaded internally, awaiting review
 *   ready           - reviewed, ready to use or send
 *   sent            - sent out for review or signing
 *   pending         - waiting on a signer or counterparty action
 *   signed_internal - executed by firm-side attorney
 *   signed_employee - signed by firm employee (HR, internal)
 *   signed_client   - signed by client
 *   signed_other    - signed by counterparty / opposing party
 *   on_hold         - paused (waiting on info, deal halted)
 *   overdue         - due_at has passed without resolution
 *   canceled        - canceled
 */
export type FirmDocumentStatus =
  | 'received'
  | 'submitted'
  | 'ready'
  | 'sent'
  | 'pending'
  | 'signed_internal'
  | 'signed_employee'
  | 'signed_client'
  | 'signed_other'
  | 'on_hold'
  | 'overdue'
  | 'canceled';

export const FIRM_DOCUMENT_STATUSES: FirmDocumentStatus[] = [
  'received',
  'submitted',
  'ready',
  'sent',
  'pending',
  'signed_internal',
  'signed_employee',
  'signed_client',
  'signed_other',
  'on_hold',
  'overdue',
  'canceled',
];

export const FIRM_DOCUMENT_STATUS_LABEL: Record<FirmDocumentStatus, string> = {
  received: 'Received',
  submitted: 'Submitted',
  ready: 'Ready',
  sent: 'Sent',
  pending: 'Pending',
  signed_internal: 'Signed (internal)',
  signed_employee: 'Signed (employee)',
  signed_client: 'Signed (client)',
  signed_other: 'Signed (other party)',
  on_hold: 'On hold',
  overdue: 'Overdue',
  canceled: 'Canceled',
};

/**
 * The five tone names, as the one hex each. Two files used to carry a
 * private five-entry map of Tailwind classes keyed by these names (the
 * document list and the status changer) and they had already drifted
 * apart on `gray`. A tone is a colour, so it resolves to a colour here
 * and the chip derives its fill and border from it.
 */
export const FIRM_TONE_COLOR: Record<
  'gray' | 'blue' | 'amber' | 'green' | 'rose',
  string
> = {
  gray: PILL_COLORS.neutral,
  blue: PILL_COLORS.info,
  amber: PILL_COLORS.waiting,
  green: PILL_COLORS.good,
  rose: PILL_COLORS.flagged,
};

export const FIRM_DOCUMENT_STATUS_TONE: Record<FirmDocumentStatus, 'gray' | 'blue' | 'amber' | 'green' | 'rose'> = {
  received: 'blue',
  submitted: 'gray',
  ready: 'blue',
  sent: 'amber',
  pending: 'amber',
  signed_internal: 'green',
  signed_employee: 'green',
  signed_client: 'green',
  signed_other: 'green',
  on_hold: 'gray',
  overdue: 'rose',
  canceled: 'rose',
};

export type FirmDocument = {
  id: string;
  firmId: string;
  name: string;
  mimeType: string;
  filePath: string;
  /**
   * Derived copy of filePath with signature boxes drawn onto it (see
   * lib/signature-anchors.ts). Null when the source PDF already had a
   * usable anchor, or when it was never parseable. This is the version
   * a signer is shown, because it is the version the final render
   * stamps.
   */
  signableFilePath: string | null;
  fileSize: number;
  version: number;
  parentDocumentId: string | null;
  uploadedBy: string | null;
  uploadedAt: string;
  tags: string[];
  caseId: string | null;
  clientUserId: string | null;
  archivedAt: string | null;
  status: FirmDocumentStatus;
  statusUpdatedAt: string;
  description: string | null;
  dueAt: string | null;
};

export type FirmSigningStatus =
  | 'draft'
  | 'sent'
  | 'partial'
  | 'completed'
  | 'canceled'
  | 'rejected'
  | 'changes_requested';

export const FIRM_SIGNING_STATUS_LABEL: Record<FirmSigningStatus, string> = {
  draft: 'Draft',
  sent: 'Awaiting signatures',
  partial: 'Partially signed',
  completed: 'Completed',
  canceled: 'Recalled',
  rejected: 'Rejected',
  changes_requested: 'Changes requested',
};

/**
 * One colour per signing state. The list and the detail page each
 * decided this for themselves and did not agree: the list coloured
 * completed green and awaiting/partial amber, while the detail page
 * painted every state the same neutral. Neither gave `rejected` or
 * `changes_requested` a colour, so a declined request read as
 * unremarkable on the list and invisible on the detail page.
 */
export const FIRM_SIGNING_STATUS_COLOR: Record<FirmSigningStatus, string> = {
  draft: PILL_COLORS.neutral,
  sent: PILL_COLORS.waiting,
  partial: PILL_COLORS.waiting,
  completed: PILL_COLORS.good,
  canceled: PILL_COLORS.neutral,
  rejected: PILL_COLORS.flagged,
  changes_requested: PILL_COLORS.waiting,
};

export type FirmSigningRequest = {
  id: string;
  firmId: string;
  documentId: string;
  requestedBy: string;
  status: FirmSigningStatus;
  message: string | null;
  sentAt: string | null;
  completedAt: string | null;
  createdAt: string;
  /**
   * SHA-256 of the document bytes captured at request-creation time.
   * Used by the audit trail to prove the bytes the signer consented
   * to match the bytes the firm later relies on. Null when the
   * request was created before the audit-trail migration shipped or
   * when the document download failed at hash time.
   */
  documentSha256: string | null;
  /**
   * Whether the signer may download a copy of what they signed. Set by
   * the firm when the request is composed and enforced server-side by
   * the copy route, not merely by hiding a button.
   *
   * Defaults to true, including for rows written before the column
   * exists: a signer keeping a copy is the ordinary expectation and
   * E-SIGN at 15 USC 7001(a)(1) is built around retention.
   */
  signerCanDownload: boolean;
  /**
   * Which signature methods this request may be signed with, frozen from the
   * dispatching template when it was created.
   *
   * Null means no restriction, which is what every request created before
   * 20260814_signature_methods.sql means and what every request for a plainly
   * uploaded document means. lib/signature-write.ts refuses a signature made
   * any other way; the signer's page reads this only so it can offer the
   * methods that will be accepted rather than letting somebody draw their name
   * and then be told.
   */
  signatureMethods: SignatureMethod[] | null;
  /**
   * Storage path to the EXECUTED copy: the PDF with each signature and
   * its date stamped onto the signature line, produced by
   * lib/signature-render.ts once the last signer is in.
   *
   * Null on any request that is not completed, and on a completed one
   * whose render failed or which predates the render pipeline. A
   * counsel surface reads it through selectSigningArtifact
   * (lib/signing-artifact.ts) rather than trusting it on its own,
   * because null on a completed request is a state that has to be
   * stated, not quietly papered over with the original.
   */
  signedFilePath: string | null;
};

export type FirmSignature = {
  id: string;
  signingRequestId: string;
  signerUserId: string | null;
  signerEmail: string;
  signerName: string | null;
  token: string;
  positionPage: number | null;
  positionX: number | null;
  positionY: number | null;
  signedAt: string | null;
  ipAddress: string | null;
  userAgent: string | null;
  signatureImagePath: string | null;
  auditHash: string | null;
  createdAt: string;
  /** Signer declined to sign: 'rejected' or 'changes_requested'. */
  response: 'rejected' | 'changes_requested' | null;
  responseNote: string | null;
  respondedAt: string | null;
  /**
   * True when an external signer must enter a one-time access code
   * (emailed separately) before the document is shown. The code hash
   * itself is never surfaced - only whether a code is required and
   * whether it has already been entered.
   */
  accessCodeRequired: boolean;
  /** When the access code was entered (consumed). Null until then. */
  accessVerifiedAt: string | null;
};

// ---------- Chat ----------

export type FirmChannelKind = 'channel' | 'dm' | 'group_dm';

export type FirmChannel = {
  id: string;
  firmId: string;
  name: string | null;
  topic: string | null;
  kind: FirmChannelKind;
  isDefault: boolean;
  createdBy: string | null;
  createdAt: string;
  /** Hydrated when listing channels for a user. */
  unreadCount?: number;
  /** Hydrated for DM/group_dm so the UI can render member names. */
  memberUserIds?: string[];
};

export type FirmChannelMember = {
  id: string;
  channelId: string;
  userId: string;
  joinedAt: string;
  lastReadAt: string | null;
};

export type FirmMessage = {
  id: string;
  channelId: string;
  userId: string;
  body: string;
  attachments: FirmMessageAttachment[];
  createdAt: string;
  editedAt: string | null;
  deletedAt: string | null;
  /** Hydrated for rendering. */
  authorDisplayName?: string | null;
  authorEmail?: string | null;
};

export type FirmMessageAttachment = {
  kind: 'image' | 'file' | 'document';
  name: string;
  size?: number;
  mimeType?: string;
  /** Either a public URL or a signed URL (file/document). */
  url?: string;
  /** For document attachments referencing firm_documents.id. */
  documentId?: string;
};

// ---------- Convenience ----------

export type FirmContext = {
  firm: Firm;
  membership: FirmMember;
};
